# Generated by Django 6.0.2 on 2026-03-02 13:45

import cadflow_workflow.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('need_by', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_VALIDACAO', 'Aguardando validação'), ('REVISAO_SOLICITADA', 'Revisão solicitada'), ('PRONTO_PRODUCAO', 'Pronto p/ Produção'), ('EM_EXECUCAO', 'Em execução'), ('TRAVADO', 'Travado'), ('FINALIZADA', 'Finalizada'), ('OBSOLETA', 'Obsoleta (substituída)')], default='AGUARDANDO_VALIDACAO', max_length=32)),
                ('priority_rank', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_revisions', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cadflow_workflow.part')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('OK', 'OK p/ construir'), ('REVISAR', 'Solicitar nova versão')], max_length=16)),
                ('limitations_text', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mfg_reviews', to=settings.AUTH_USER_MODEL)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfg_review', to='cadflow_workflow.partrevision')),
            ],
        ),
        migrations.CreateModel(
            name='BlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_from_status', models.CharField(blank=True, max_length=32)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks_resolved', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cadflow_workflow.partrevision')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to=cadflow_workflow.models.revision_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cadflow_workflow.partrevision')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='partrevision',
            index=models.Index(fields=['status'], name='cadflow_wor_status_6af7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='partrevision',
            index=models.Index(fields=['is_current'], name='cadflow_wor_is_curr_c22370_idx'),
        ),
        migrations.AddIndex(
            model_name='partrevision',
            index=models.Index(fields=['part', 'status'], name='cadflow_wor_part_id_959844_idx'),
        ),
        migrations.AddConstraint(
            model_name='partrevision',
            constraint=models.UniqueConstraint(fields=('part', 'revision_no'), name='uniq_part_revisionno'),
        ),
        migrations.AddConstraint(
            model_name='partrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('part',), name='uniq_current_revision_per_part'),
        ),
        migrations.AddConstraint(
            model_name='blockevent',
            constraint=models.UniqueConstraint(condition=models.Q(('unblocked_at__isnull', True)), fields=('revision',), name='uniq_active_block_per_revision'),
        ),
    ]
